name: "Release binary and Docker image"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  PROJECT_NAME: telegram-msg-forwarder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build binary
        run: |
          docker pull messense/rust-musl-cross:x86_64-musl && \
          docker run --rm -v "$(pwd)":/home/rust/src messense/rust-musl-cross:x86_64-musl cargo build --release && \
          cp target/x86_64-unknown-linux-musl/release/$PROJECT_NAME ./server && \
          tar -zcf $PROJECT_NAME.tar.gz server

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.PROJECT_NAME }}.tar.gz

      - name: Generate changelog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          npx changelogithub

      - name: Get Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.actor }}/${{ env.PROJECT_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
